plugins = []
functionsDirectory = "C:\\Users\\sabar\\source\\repos\\sabarivelanganesan\\Portfolio\\Portfolio-v2\\gsv-portfolio-v2\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\sabar\\source\\repos\\sabarivelanganesan\\Portfolio\\Portfolio-v2\\gsv-portfolio-v2\\\tbuild"
publishOrigin = "config"
command = "npm run build"
commandOrigin = "config"
functions = "C:\\Users\\sabar\\source\\repos\\sabarivelanganesan\\Portfolio\\Portfolio-v2\\gsv-portfolio-v2\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]